services:
  - type: web
    name: wsp-flow-backend
    env: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm run start:prod
    healthCheckPath: /api/v1/whatsapp/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_PREFIX
        value: api/v1
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRATION
        value: 1d
      - key: JWT_REFRESH_EXPIRATION
        value: 7d
      - key: BAILEY_SESSION_DIR
        value: ./auth_info_baileys
      - key: BAILEY_AUTO_RECONNECT
        value: "true"
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-5.6-luna
      - key: CULQI_PUBLIC_KEY
        sync: false
      - key: CULQI_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: CORS_ORIGIN
        value: "*"
